modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="kilukimod"
version="1.0.0"
displayName="KilukiMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="KawaZaa, MCreator"

[[dependencies.kilukimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



